# Generated by Django 4.2.10 on 2024-11-13 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('इमाम साहब की सैलरी में', 'इमाम साहब की सैलरी में'), ('मस्जिद में खर्च', 'मस्जिद में खर्च'), ('बिजली/बल्ब/तार/पंखा', 'बिजली/बल्ब/तार/पंखा'), ('साउंड सिस्टम', 'साउंड सिस्टम'), ('ईद में सजावट', 'ईद में सजावट'), ('कुर्बानी में सजावट', 'कुर्बानी में सजावट'), ('चापाकल', 'चापाकल'), ('वाइपर खरीदने में', 'वाइपर खरीदने में'), ('झाड़ू', 'झाड़ू'), ('ताला/चाबी', 'ताला/चाबी'), ('लोटा', 'लोटा'), ('पेंटिंग', 'पेंटिंग'), ('ईंट', 'ईंट'), ('गिट्टी', 'गिट्टी'), ('बालू', 'बालू'), ('सीमेंट', 'सीमेंट'), ('छड़', 'छड़'), ('मिस्त्री/लेबर', 'मिस्त्री/लेबर'), ('टाइल्स', 'टाइल्स')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NamazTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fajr_time', models.TimeField()),
                ('dhuhr_time', models.TimeField()),
                ('asr_time', models.TimeField()),
                ('maghrib_time', models.TimeField()),
                ('isha_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
